niklasvh/html2canvas

site/documentation.html

fix typing error

---

README.md

since it will be better for high-res screens

change build badge to SVG

---

src/ListItem.js

This commit remove KOREAN_NEGATIVE value's unintended space.

Remove unintended space

---

src/Feature.js
src/ResourceLoader.js
tests/reftests/ignore.txt

fix: safari data url taints

---

src/core/cache-storage.ts
src/index.ts
src/render/canvas/canvas-renderer.ts
src/render/canvas/foreignobject-renderer.ts

fixes #1854
fixes #1855
fixes #1857

fix: typescript options type definition

---

src/render/canvas/canvas-renderer.ts
tests/reftests/border/solid.html

fix: correctly render partial borders (fix #1920)

---

src/render/stacking-context.ts
tests/reftests/zindex/z-index19.html

fix: nested z-index ordering

---

src/index.ts

fix: null backgroundColor option as transparent

---

src/css/types/functions/counter.ts
src/dom/document-cloner.ts
src/global.d.ts

fixes #1993
fixes #1649
fixes #1827

fix: safari pseudo element content parsing

---

src/dom/document-cloner.ts
src/index.ts
tests/reftests/images/images.html

fix: image loading="lazy" 

---

src/css/property-descriptors/__tests__/font-family.ts
src/css/property-descriptors/font-family.ts
src/dom/document-cloner.ts
src/dom/node-parser.ts
tests/reftests/images/svg/native_only.html

Fix: #2151
Fix: #1629
Fix: #1724
Fix: #1463 
Fix: #1709

fix: external styles on svg elements

---

src/render/canvas/canvas-renderer.ts
src/render/effects.ts
src/render/stacking-context.ts
tests/reftests/overflow/overflow.html

fix: opacity with overflow hidden

---

src/index.ts

Fix: #2570 
Fix: #2382
Fix: #2381

fix: logger unique names

---

src/render/canvas/canvas-renderer.ts

fix: text-shadow position with baseline

---

src/dom/node-parser.ts
tests/reftests/webcomponents/autonomous-custom-element.js
tests/reftests/webcomponents/slot-element.js
tests/reftests/webcomponents/webcomponents.html

Fixes #2020 
Fixes #865
Fixes #430

feat: support for custom and slot elements

---

src/dom/replaced-elements/svg-element-container.ts
tests/reftests/images/svg/native_only.html

fix: responsive svg images

---

src/dom/document-cloner.ts

feat: allow access to reference element in onclone

---

src/render/canvas/canvas-renderer.ts

fix: text position for form elements and list markers

---

src/render/canvas/canvas-renderer.ts

fix: this.canvas.ownerDocument is undefined

---

src/css/layout/text.ts
tests/reftests/text/text.html

fix: word-break seperators

---

package-lock.json
package.json
tests/reftests/text/text.html

Apply fix from https://github.com/niklasvh/css-line-break/pull/16

fix: emoji line breaking (fix #1813)

---

src/css/types/image.ts
tests/reftests/background/linear-gradient2.html

fix: none image type

---

src/core/cache-storage.ts

fix: type import that is only available ts 3.8 or higher

---

src/render/canvas/canvas-renderer.ts

fix: radial gradient ry check

---

src/css/types/functions/counter.ts
tests/reftests/pseudo-content.html

Fixes #2639
Fixes #2121
Fixes #1478

fix: parsing counter content in pseudo element

---

src/dom/document-cloner.ts
src/index.ts

fix: correctly handle allowTaint canvas cloning

---

src/css/IPropertyDescriptor.ts
src/css/index.ts
src/css/property-descriptors/duration.ts
src/css/property-descriptors/overflow-wrap.ts
src/css/syntax/tokenizer.ts
src/css/types/index.ts
src/css/types/time.ts
src/dom/element-container.ts
tests/reftests/animation.html

fix: finish animation/transitions for elements

---

src/css/index.ts
src/css/property-descriptors/direction.ts
src/render/canvas/canvas-renderer.ts

Fixes #2488
Fixes #2529
Fixes #1460
Fixes #686

feat: add rtl render support

---

src/css/index.ts
src/css/property-descriptors/duration.ts
src/dom/element-container.ts
tests/reftests/animation.html

fix: multi arg transition/animation duration

---

src/css/syntax/tokenizer.ts

fix: reduce SLICE_STACK_SIZE to 50k

---

src/core/features.ts
src/css/layout/bounds.ts
src/css/layout/text.ts
src/render/canvas/canvas-renderer.ts

Fixes: #2731
Fixes: #2696
Fixes: #2670
Fixes: #2623
Fixes: #2448
Fixes: #2298
Fixes: #2271
Fixes: #2177

feat: use native text segmenter where available

---

rollup.config.ts
tests/server.ts

fix: source maps
