niklasvh/html2canvas

src/nodecontainer.js

IE10+ returns a matrix3d instead of matrix. Changed the regex to also check for matrix3d and convert matrix3d to a 'normal' matrix

Transform matrix for IE

---

src/color.js
src/gradientcontainer.js
src/lineargradientcontainer.js
src/webkitgradientcontainer.js
tests/cases/background/linear-gradient.html
tests/mocha/gradients.js
tests/mocha/parsing.html

Also:
- Cleans up color stop and linear gradient regular expressions.
- Handles percentage-based linear gradient positions (fixes Firefox).
Fixes niklasvh/html2canvas#469.

Linear gradients now parse color names

---

src/Renderer.js
src/parsing/padding.js
tests/reftests/background/origin.html

**Summary**
Add support for background-origin: content-box and fix for problem related to background image size with background-origin set to padding-box or content-box and background-size set to cover/contain.
Added tests/reftests/background/origin.html.
**Code formatting**
Please make sure that code adheres to the project code formatting. Running `npm run format` will automatically format your code correctly.

Added support for background-origin: content-box, fixed background-origin related background sizes

---

src/Gradient.js
src/Renderer.js
src/parsing/background.js
tests/reftests/background/linear-gradient2.html

**Summary**
Added support for gradient background size (respecting background-size and background-origin), and fixed linear gradient angle when vendor prefix is used (the 0° angle then points due East, in the finalized W3C specification, it points due North).
Repeating gradients are not yet supported.
Better support for linear gradient backgrounds.
Added tests/reftests/background/linear-gradient2.html

Added support for gradient background size and fixed linear gradient angle when vendor prefix is used

---

src/renderer/CanvasRenderer.js

Fix underline positioning.
Since `ctx.textBaseline` is set to 'bottom', underlines need to be positioned relative to the bottom of the text, not the top.

Bugfix: Fix underlines

---

package.json
src/ListItem.js
src/NodeParser.js
src/Util.js
tests/reftests/list/liststyle.html

**Summary**
This PR adds support for rendering the enumerations (bullets, numbers, etc.) in ordered and unordered lists and for list style images.
For the actual formatting, an external package is used (https://www.npmjs.com/package/liststyletype-formatter), I hope that's OK.
More accurate rendering of (un)ordered lists.
Added tests/reftests/list/liststyle.html, which tests some more list styles in addition to the already existing tests, in the tests/reftests/list folder.
Fixes #177 
Fixes #308

Added support for rendering enumerations in ordered lists and for list-style

---

docs/features.md
package.json
src/Clone.js
src/PseudoNodeContent.js
tests/node/pseudonodecontent.js
tests/reftests/pseudo-content.html

**Summary**
This PR improves the support for the `content` style declaration for pseudo-elements.
The following was added to the existing support of strings and `url()`:
Better support for `content`.
This PR is not yet exhaustive, though (i.e., `content` still supports a wider range of item types).
* Added tests/reftests/pseudo-content.html
* Added a mocha test, tests/node/pseudonodecontent.js, to test the content parser.
Fixes #971

Improved support of "content" for pseudo-elements

---

.flowconfig
docs/features.md
package-lock.json
package.json
src/NodeContainer.js
src/TextBounds.js
src/Unicode.js
src/parsing/lineBreak.js
src/parsing/overflowWrap.js
src/parsing/word-break.js
tests/reftests/text/line-break.html
tests/reftests/text/overflow-wrap.html
tests/reftests/text/word-break.html

**Summary**
Implement unicode line-breaking
Fixes #752 
Fixes #334 
Fixes #664
Fixes #1245

Implement unicode line-breaking

---

src/Bounds.js

**Summary**
* [X ] Bug 1: border radius calculation
When creating a half circle using border-radius like this:
`border-radius: 100% 100% 0 0 / 200% 200% 0 0;`
The current code limits the values to go to a maximum of half the height/width of the element you're putting the radius on. 
Browsers render this differently: They check if the combined values of corners exceed the width or height of the element. If so, they scale all corners down to keep the ratio of the biggest corner in tact. See: https://jsfiddle.net/jkrielaars/1uymfqae/1/
Demonstrate how the issue/feature can be replicated. For most cases, simply …

updated calculation of border-radius

---

src/renderer/CanvasRenderer.js

This reverts commit 0c8d38d9c0659f532358a0d0c3250c1f813005fd.
As described [here](https://github.com/niklasvh/html2canvas/pull/1292#issuecomment-360700136), the underline fix I submitted was superseded by 38749bc. [This fiddle](http://jsfiddle.net/8rjbyqgj/) submitted by @FDIM illustrates that it is now causing a problem.
Related: #1292, #1364, #1394.

Revert "Fix underlines, relative to 'bottom' baseline"

---

src/ResourceLoader.js

**Summary**
**motivation**
fix a bug: can not load a image resource when the image's url is blob format
**problem reproduce**
https://jsfiddle.net/mapleeit/y6m87qwe/4/

support blob image resources in non-foreignObjectRendering mode

---

src/Clone.js

https://github.com/niklasvh/html2canvas/issues/1374
Reproduced the above issue and located the cause, it happens in the createElementClone function when it attempts to access the cssText property, for some reason when using font-awesome, an element with fa-spin throws this error in IE when accessing the property.
Wrapping the property access in a try catch solves the immediate issue.

IE11 Member not found fix Wrap accesing the cssText property in a try...catch

---

package.json

**Summary**
This PR implements the following features:
The `main` field in package.json points to `'dist/npm/index.js'`, which is ideal for CommonJS projects, however will fail on ES/browser bundlers because of the use of the undefined `process.env.NODE_ENV`.
This PR adds the fields `module` and `browser` to package.json, as defined [here](https://stackoverflow.com/a/42817320/4080966) and [here](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md#typical-usage) (module) and [here](https://github.com/defunctzombie/package-browser-field-spec) (browser). Both fields point to `dist/html2canvas.js`, which is built as UMD and will work with any format.
Create a new project, use ES syntax to `import` html2canvas, and use rollup or similar to bundle into …

Add support for ES and browser bundlers

---

src/renderer/CanvasRenderer.js

In our experience, it's possible for the colorstop.stop to be less than zero, but only in Firefox. When this happens, you get the dreaded "IndexSizeError: Index or size is negative or greater than the allowed amount".
This often manifests as -0 or a very small negative number, so it seems pretty safe to just force this to zero.
Replicating this error is not easy and I don't currently have a live site to demonstrate it with, so I'll try to find out more. We're currently patching dist/html2canvas.js.

Enforce colorstop min 0

---

docs/faq.md

**This update the FAQ -  Why is the produced canvas empty or cuts off half way through?**

Update faq.md - Why is the produced canvas empty or cuts off half way through?

---

src/Clone.js

Fixes the problem outlined in https://github.com/niklasvh/html2canvas/issues/1502#issuecomment-466501044
**Test plan (required)** - TODO
Demonstrate how the issue/feature can be replicated. For most cases, simply adding an appropriate html/css template into the [reftests](https://github.com/niklasvh/html2canvas/tree/master/tests/reftests) should be sufficient. Please see other tests there for reference.

Prevent unhandled promise rejections for hidden frames

---

src/Clone.js

**Summary**
Wrap accesses to .sheet.cssRules in a try...catch block. On Firefox, this access can cause a DOMException to be thrown ('SecurityError') which interrupts the entire process. Log-and-resume to avoid it.
* [node.sheet.cssRules accessed outside of try-catch, so the thrown DOMException is uncaught #1673](https://github.com/niklasvh/html2canvas/issues/1673) Bug 1
The uncaught exception means that the entire html2canvas operation is interrupted and no image is produced. At least for our application, the cssRule can be safely ignored.
I'm still working on this. Adding a file into tests/reftests isn't …

Wrap .sheet.cssRules access in try...catch.

---

src/renderer/ForeignObjectRenderer.js

**Summary**
On high resolution displays (where `defaultView.devicePixelRatio` is greater than `1`), the rendered output will only take some fraction of the entire canvas.  This is because twice as many pixels need to be written out.  
This calls `this.context.scale(...)` to normalize coordinate system to use css pixels. This technique is shown on [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#Example). This fixes the problem.
I'm not sure how to test this without running tests on a machine that has a high resolution display.
Fixes #
Closes #1781

Sets the context scale for high resolution displays

---

src/css/syntax/tokenizer.ts

fix: stack exceeding for css tokenizer

---

src/css/property-descriptors/background-image.ts
src/css/syntax/parser.ts
src/css/syntax/tokenizer.ts
src/css/types/color.ts
src/css/types/functions/-webkit-gradient.ts
src/css/types/image.ts
src/dom/document-cloner.ts

**Summary**
Hi, this PR makes html2canvas ignore unsupported background image functions encountered while parsing the document tree so that the screenshot will get generated even when the document includes such functions.
It fixes the following issues:
This issue can be reproduced here:
http://jsfiddle.net/yh4L67bf/
Fixes #1865

feat: ignore unsupported image functions

---

src/dom/replaced-elements/iframe-element-container.ts
src/render/canvas/canvas-renderer.ts

**Summary**
- if an iframe has not specified width or height it parsed to NaN
- Canvas drawImage throw error when try to draw 0 size image
Fixes #1668

fix: zero size iframe rendering (#1668)

---

src/css/property-descriptors/display.ts

A similar PR may already be submitted!
Please search among the [Pull request](https://github.com/niklasvh/html2canvas/pulls) before creating one.
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
Before opening a pull request, please make sure all the tests pass locally by running `npm test`.
**Summary**
Since IE uses the -ms-grid display property instead of the grid property, the display property list was missing this tag. This caused empty rendering for grid layouts on IE.
* [ x ] Bug 1
In IE with a grid layout the library produces an empty image, due to the …

add missing -ms-grid display property to support IE grid layouts

---

src/index.ts

> A similar PR may already be submitted!
> Please search among the [Pull request](https://github.com/niklasvh/html2canvas/pulls) before creating one.
> Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
> Before opening a pull request, please make sure all the tests pass locally by running `npm test`.
**Summary**
> Explain the **motivation** for making this change. What existing problem does the pull request solve?
`html2canvas` causes JavaScript applications that use server-side rendering (e.g. via Next.js, Nuxt, Gatsby, Gridsome) to break as the `CacheStorage.setContext(window)` call that is executed on import tries to access the `window` variable that does not …

Fix error in server-side rendering (SSR)

---

karma.conf.js

**Summary**
Azure Pipelines builds for `html2canvas` under Chrome on Linux appear to have been failing since late February, and perhaps a little earlier ([ref](https://github.com/niklasvh/html2canvas/pull/2132/checks?check_run_id=475396574)). 
A [recent build log](https://dev.azure.com/niklasvh/html2canvas/_build/results?buildId=256&view=logs&jobId=1ecc60e2-a730-5598-9e07-c12e2a8ba1e2&j=1ecc60e2-a730-5598-9e07-c12e2a8ba1e2&t=442b2b39-a15b-50fe-6fa6-917f1ac11af5) seems to indicate that Chrome has trouble launching, perhaps due to issues connecting to the local X server (display) infrastructure.
```
13 04 2020 21:10:28.427:ERROR [launcher]: Chrome stdout: 
13 04 2020 21:10:28.427:ERROR [launcher]: Chrome stderr: [4250:4250:0413/211026.555114:ERROR:edid_parser.cc(102)] Too short EDID data: …
```

Azure Pipelines: Resolve Chrome Linux build failures

---

azure-pipelines.yml
ci/browser-tests.yml
karma.conf.js
package-lock.json
package.json

**Summary**
As per a recent Microsoft's Azure DevOps [blog post](https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/), build images for `macOS 10.13` now [appear to have been removed](https://dev.azure.com/niklasvh/html2canvas/_build/results?buildId=257&view=logs&j=2d670fa7-f2eb-599e-bd33-f0da06e227c7) from Azure Pipelines.
```
##[warning]An image label with the label macOS-10.13 does not exist.
,##[error]The remote provider was unable to process the request.
```
This is causing macOS-related builds to fail.
This pull requests updates the base image for those builds to the more recent `macOS-10.14`.
The result of Azure Pipeline builds on this pull request for macOS-derived test suites should indicate whether the change is …

Azure Pipelines: upgrade from macOS 10.13 -> 10.14

---

src/css/property-descriptors/__tests__/font-family.ts
src/css/property-descriptors/font-family.ts

**Summary**
As noted in #1881, rendering of some named fonts using `html2canvas` can be troublesome.
Many of the reported examples relate to free distribution of the [FontAwesome](https://fontawesome.com/) version 5 fonts.  Web applications using this font frequently set the CSS-based `font-family` property to the string `Font Awesome 5 Free`, as included in some of the default stylesheets ([ref](https://github.com/FortAwesome/Font-Awesome/blob/4e6402443679e0a9d12c7401ac8783ef4646657f/css/regular.css#L6)).
The root cause of the issues encountered when using Font Awesome 5 Free and `html2canvas` in combination is that the latter's [`font-family` parser](https://github.com/niklasvh/html2canvas/blob/4dd4a69c7a2e46c54b5d223fbc94fa4066f19a3c/src/css/property-descriptors/font-family.ts#L14-L16) …

Concatenate contiguous font-family tokens

---

src/render/stacking-context.ts
tests/reftests/zindex/z-index20.html

**Summary**
Fixed the wrong calculation of the order of layers when the z-index is equal

fix(z-index):z-index order

---

src/render/bound-curves.ts
tests/reftests/border/radius.html

**Summary**
This PR fixes the following **bugs**
I added a `.box7` in refstests/border/radius.html

fix top right border radius

---

src/css/property-descriptors/border-style.ts
src/css/property-descriptors/display.ts
src/global.d.ts
src/render/border.ts
src/render/bound-curves.ts
src/render/canvas/canvas-renderer.ts
tests/karma.ts

**Summary**
- Fixes incorrect rounded border box
- Change parameter value of `XxxXxxPaddingBox` correctly in `bound-curves.ts`
- Dashed border style
- Calculate a dash length and space length (I referred to the Chromium source code)
- Draw dash line on border outer path with double thickness and clip
- If corner is rounded draw additional line to fill the gaps between the sides.
- Dotted border style
- Added `XxxXxxBorderStroke` in `bound-curves.ts`
- Calculate a dash length and space length (I referred to the Chromium source code)
- Draw dash line with round line cap on border center path
- Double border style
- Added `XxxXxxBorderDoubleOuterBox` and `XxxXxxBorderDoubleInnerBox`
- Fill outer box and inner box
**Test plan …

add features for border-style dashed, dotted, double.

---

src/core/cache-storage.ts

**Summary**
Currently, proxy url's cannot have parameters. 
2098
If a proxy url contains a parameter such as:
http://abc.com/myproxy.jsp?myparam=foo
html2canvas will call the proxy using the following url:
http://abc.com/myproxy.jsp?myparam=foo?url=abc.com....
Notice there are two question marks in the url which is incorrect. The second parameter should begin with an ampersand.
The code had automatically put a question mark (?) after the proxy url. I fixed the code to check whether there is already a parameter at the end of the url. This was properly done in the the 0.5 version:
Pass a proxy url which ends …

Allow proxy url with parameters

---

src/dom/document-cloner.ts

fix: iframe load to ensure images are loaded

---

src/dom/document-cloner.ts

fix: don't copy 'all' css property

---

docs/features.md
src/css/index.ts
src/css/property-descriptors/__tests__/paint-order.ts
src/css/property-descriptors/paint-order.ts
src/css/property-descriptors/webkit-text-stroke-color.ts
src/css/property-descriptors/webkit-text-stroke-width.ts
src/render/canvas/canvas-renderer.ts

Based on original work in #1540
Fixes #1540
Fixes #2479
Fixes #2009

feat: add support for webkit-text-stroke and paint-order

---

src/css/index.ts
src/dom/document-cloner.ts
src/dom/element-container.ts
tests/reftests/animation.html

fix: disable transition properties

---

src/dom/document-cloner.ts

docs: add warning for webgl cloning with preserveDrawingBuffer=false

---

src/css/property-descriptors/overflow.ts
src/render/canvas/canvas-renderer.ts
src/render/effects.ts
src/render/stacking-context.ts
tests/reftests/overflow/overflow.html

fix: overflows with absolutely positioned content

---

src/render/font-metrics.ts

A similar PR may already be submitted!
Please search among the [Pull request](https://github.com/niklasvh/html2canvas/pulls) before creating one.
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
Before opening a pull request, please make sure all the tests pass locally by running `npm test`.
**Summary**
Fix "offsets" text when font is big enought and screen is width of mobile screen bug 
This PR fixes/implements the following **bugs**
html2canvas "offsets" text when font is big enough and screen is small;
Tested with a small mobile screen width and font size of 100px;
The problem does not occurs when screen is larger and it does not depends on the size of the container.
sample following …

Fix "offsets" text when font is big enought and screen is width of mobile screen bug 

---

src/dom/document-cloner.ts
src/dom/node-parser.ts
tests/reftests/webcomponents/autonomous-custom-element.js
tests/reftests/webcomponents/webcomponents.html

Fixes #2759
Fixes #2356
Fixes #2325
Fixes #2058
Fixes #1726

fix: adopted stylesheets

---

src/css/layout/bounds.ts

fix: Properties x and y of BoundingRect is undefined in old browser like Chrome/52.0.2743.100
Fixes: #2770
Fixes: #2733

fix: getBoundingClientRect x and y properties in older browsers
